### ISSUE TITLE
KickThreshold is too short so new candidates got kicked before they are able to author blocks

### ISSUE THREAD

**Issue by xlc** [paritytech/statemint#87]
https://github.com/paritytech/statemint/blob/9664809ad5de6ce43b6b78a6b3d12fbfece7f147/runtime/statemine/src/lib.rs#L610-L611

New candidates can only be author blocks after 2 sessions, but threshold is just 1 period.

And why KickThreshold needs to be a multiple of session?

Should really only track last authored blocks & kick inactive one only for current collator.

**Comment by joepetrowski** [comment]
The threshold is 1 era (6 sessions): https://github.com/paritytech/statemint/blob/9664809ad5de6ce43b6b78a6b3d12fbfece7f147/runtime/statemine/src/lib.rs#L566

**Comment by JesseAbram** [comment]
As you register as a candidate you get that [block written in](https://github.com/paritytech/statemint/blob/master/pallets/collator-selection/src/lib.rs#L301) so you can't be kicked out on that session 

> And why KickThreshold needs to be a multiple of session?

This is because the new round of collators are chosen on[ every session](https://github.com/paritytech/statemint/blob/master/pallets/collator-selection/src/lib.rs#L416) so you get selected or kicked when that happens, so if it isn't this will lead to unexpected results

> New candidates can only be author blocks after 2 sessions, but threshold is just 1 period.

On every session we reset the [authorities](https://github.com/paritytech/statemint/blob/master/pallets/collator-selection/src/lib.rs#L407)

**Comment by xlc** [comment]
@joepetrowski a session is 6 hours>

https://github.com/paritytech/statemint/blob/9664809ad5de6ce43b6b78a6b3d12fbfece7f147/runtime/statemine/src/lib.rs#L592

**Comment by xlc** [comment]
@JesseAbram 

say session length & kick threshold are 100 blocks

Alice join at block 100, session 1. She will be collator at session 3, block 300. But at block 300, the last authored block for Alice is 100 and 100 + 100 is less than 300?

**Comment by JesseAbram** [comment]
I am not sure where you are getting the session 1 session 3. There is no logic for that in collator selection and none I could see in session and aura, although @kianenigma is the expert there if I am missing something. 

Alice joins at session one, she is a collator in session 2 and as long as she produces a block in that session she will not be kicked.

**Comment by xlc** [comment]
Currently there is hardcoded 1 session delay. i.e. the change won't be applied on next session, but the one after next.

https://github.com/paritytech/polkadot-sdk/issues/463

**Comment by JesseAbram** [comment]
ahh I see now, ok the tests were always making 4 author which is why they missed it, will create a PR that adds either the (session or the kickThreshold, still thinking about what is best) to the init block.

**Comment by xlc** [comment]
FYI we are going to use a different way to handle this https://github.com/AcalaNetwork/Acala/pull/1049

**Comment by kianenigma** [comment]
Solutions:

1. when onboarding a collator, if possible, we should determine when they will become 'active' and set that as their last authored block. Although this might be tricky. 

2. kicking is a simple replacement for the im-online pallet. Ideally, it should be a new pallet iself that **directly connects** to the session pallet. Being a collator in `collator-selection` does _not_ mean that you are actually actively _authoring blocks_. Therefore, the `collator-selection` listening for authorship events and making decisions based on it is _inherently_ flawed. To the contrary, being a validator in `pallet-session` _does_ mean that you are authoring blocks. So ideally there should be a new pallet to handle this, which _directly_ connects to `pallet-session`, instead of _living inside_ `collator-selection`.

For now, I recommend

1. disable this feature, or set its threshold to something high (+ 2 sessions)
2. implement one of the proposals above.

**Comment by JesseAbram** [comment]
closed with paritytech/substrate#88 will open another issue to talk about a better solution based on the comment from Kian
